# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 29f0339b9c68671a78c3d20aeaa704e22b5ecda66a7cad27820ab30e1b942708912d774488e93fe429da0ddcb270d2594d267544a379618b1f42ad52e25db4b6

test:
  secret_key_base: 1566375e0ff05114fe421d11686a1907308cd6bc3bdf02b37ceaf770f832a08a16148fab0e6cd938ecf64ff2d79fcde2680149c878879ec55f652c17b6441faf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
